// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMm_-8b5O7AobhBT3DuYWXY1xBZQdq2M',
    appId: '1:1033353210793:web:b682139cd02c482e6eb2b8',
    messagingSenderId: '1033353210793',
    projectId: 'insta-5fc40',
    authDomain: 'insta-5fc40.firebaseapp.com',
    storageBucket: 'insta-5fc40.appspot.com',
    measurementId: 'G-S6CV2VP5L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtEAtzuR6NZoy88NoWqOe6y3k14R3s14Q',
    appId: '1:1033353210793:android:f0e030b2d4d411816eb2b8',
    messagingSenderId: '1033353210793',
    projectId: 'insta-5fc40',
    storageBucket: 'insta-5fc40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEIWbniylnnnxsbBtuWRkD5FCU9LUxInE',
    appId: '1:1033353210793:ios:460d30e3dcdec3386eb2b8',
    messagingSenderId: '1033353210793',
    projectId: 'insta-5fc40',
    storageBucket: 'insta-5fc40.appspot.com',
    iosClientId: '1033353210793-7nr999o6c3n1fbtd2ek7as52lv1rbpvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEIWbniylnnnxsbBtuWRkD5FCU9LUxInE',
    appId: '1:1033353210793:ios:98b11367fcef565e6eb2b8',
    messagingSenderId: '1033353210793',
    projectId: 'insta-5fc40',
    storageBucket: 'insta-5fc40.appspot.com',
    iosClientId: '1033353210793-jblskcvb206s77h46lvejpjt28um2q95.apps.googleusercontent.com',
    iosBundleId: 'com.example.main.RunnerTests',
  );
}
